title: "Markdown 101"
url: "https://www.markdown101.com" # site url
baseurl: "" # apply repo name if use it under gh-pages branch
host-name: "github"
host-url: "https://github.com"
google-analytics: "G-HJJC69D2LG"
google-adsense: "ca-pub-8257033830485278"

repo: "https://github.com/markdown101/markdown101"
comments: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap

collections:
  basic-syntax:
  extended-syntax:
  tools:
    output: true
    permalink: /tools/:title/

defaults:
  - scope:
      type: tools
    values:
      layout: tool

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

# Author settings
author:
  name: "Billow Wang"

# social settings
og_locale: "zh_CN"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..3

exclude:
  [
    "vendor",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE.txt",
    "Rakefile",
    "netlify.toml",
  ]
